name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: /newman-action@master
    name: Install Newman
    run: |
      npm install -g newman
      npm install -g newman-report-htmlextra  
    with:
    apiKey: ${{ secrets.POSTMAN_MOCK_API_KEY }}
    collection: Mock_Test_Suite.postman_collection.json
    environment: Test_Mock.postman_environment.json
    
