name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
            node-version: "18"
      - name: Install latest uuid npm
        run: |
          npm install uuid@7.0.3 -g
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run POSTMAN collection
        run: |
         newman run Mock_Test_Suite.postman_collection.json -e Test_Mock.postman_environment.json --reporter-htmlextra-export "newman/HTML_report.html" --insecure --verbose
         echo $?
    
