name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Newman
        run: |
          npm install -g newman
          npm i newman-reporter-htmlextra
      - name: Run POSTMAN collection
        run: |
         newman run Mock_Test_Suite.postman_collection.json -e Test_Mock.postman_environment.json -r htmlextra 
    
